puppetlabs/puppetlabs-peadm

- plans/configure.pp
The task doesn't deal with Booleans natively right now, but it will pass
a boolean through as the string "true" or "false" transparently. In
order to present the correct UX to the end user when writing plan
parameter files, make the plan take a Boolean now.
We'll fix the task to natively use Booleans when we change to Bolt apply
for this, instead of using the task.
> Make manage_environment_groups configur param bool

- plans/configure.pp
This lets the plan run to completion successfully, if bolt is being
executed on the primary master, without failing due to the orchestrator
restart.
> Implement local transport option for configure

- tasks/configure_node_groups.json
- tasks/configure_node_groups.sh
This pattern should simplify the wrapping of a Puppet class.
(Also modifies the task input type back to Boolean, I think that got lost in a rebase somewhere)
> Implement pattern to avoid escaping $

- plans/configure.pp
In the plan the param is listed as a Boolean rather than what we used in the task (String)
> Bugfix for configure_node_groups in the configure plan

- plans/configure.pp
- tasks/enable_replica.json
- tasks/enable_replica.sh
- tasks/provision_replica.json
- tasks/provision_replica.sh
This will allow you to pass a token_file to provision_replica and enable_replica.
This will also expose the param through the configure plan.
> Adding tokenfile option

- documentation/install_and_configure_without_ha.md
- manifests/setup/node_manager.pp
- plans/configure.pp
- plans/init.pp
- plans/install.pp
- plans/upgrade.pp
- tasks/configure_node_groups.sh
- templates/puppetdb_database-pe.conf.epp
This update adds an optional ha parameter (default = true) and conditionally performs the HA steps in the install, configure, and upgrade plans. There should be no impact to the existing functionality.
Please see [SLV-365](https://tickets.puppetlabs.com/browse/SLV-365) for context regarding the SLV team's need for this feature in provisioning environments for testing with [gatling-puppet-load-test](https://github.com/puppetlabs/gatling-puppet-load-test).
Additonally, the [`provision_pe_xl_nodes.rb`](https://github.com/billclaytor/gatling-puppet-load-test/blob/SLV-504/docs/abs_utils.md#provision_pe_xl_nodesrb) script has been added to GPLT as part of SLV-365 (see [SLV-483](https://tickets.puppetlabs.com/browse/SLV-483)) to assist in the provisioning of AWS EC2 hosts and creation of the …
> (SLV-365) Update the install, configure, and upgrade plans in the pe_xl module to make ha optional

- tasks/hostname.sh
Using `hostnamectl --transient` doesn't *always* return the FQDN, which is what the plans are usually expecting. `hostname -f` is a more reliable way of doing this.
Fixes #22
> Changed for more reliable hostname resolution

- plans/unit/install.pp
"puppetserver ca --certname <null>".  The inline template is adding a comma
and when it goes to run the next iteration it has no value for
the certname, causing a failure.  This is for a monlithic-master.
> Added "if" to not run CA sign on empty certname

- README.md
- installer/primary-master/csr_attributes.yaml
- installer/puppetdb-database/csr_attributes.yaml
- manifests/setup/node_manager.pp
- plans/unit/install.pp
The pp_role trusted fact is the most-likely-to-be-used trusted fact we
have. It's not a good idea to require the use of this one for peadm
configuration to work.
Instead, encode the information we need for component identification
into pp_application. Use puppet/ as a prefix, and attach whatever
component role a node has after that.
There's a good argument that we shouldn't use pp_application either.
We're already using it though so we don't lose anything this way, and we
gain the benefit of not using pp_role anymore. So shipping this as an
incremental improvement, with room for more improvement in the future.
> Remove use of pp_role

- functions/target_host.pp
- functions/target_name.pp
- plans/unit/configure.pp
- plans/unit/install.pp
- tasks/filesize.sh
This commit includes the changes that were required to automate
the deployment of the PE XL architecture when Bolt and Terraform
were linked together on macOS, targeted at GCP. The use case
being a single Bolt plan that can quickly stamp out new
infrastructure for customers.
Reasoning for filesize.sh change is because of parameter
mismatches between Linux and macOS. Other changes are a result
of needing to access nodes using external IP address when
initiating automation from outside the cloud provider, e.x. your
laptop and requiring that all services are wired together using
internal DNS names.
> Deploy combined with GCP, macOS, Terraform

- manifests/setup/node_manager.pp
Turns out it doesn't quite work to use the high-level parameter for the
compilers.
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Error 500 on SERVER: Server Error: Classification of <replica> failed due
to a classification conflict: The node was classified into groups named:
"PE Master B"
"PE Infrastructure Agent"
"All Environments"
"PE HA Replica"
These groups defined conflicting values for class parameters for the classes:
"puppet_enterprise"
> Partially revert fcd04d0

- documentation/basic_usage.md
- plans/action/configure.pp
- plans/action/install.pp
- plans/provision.pp
The "action" plans subdirectory contains unit actions that can be
performed, and chained together by higher-level plans. While the term
"unit" is probably the more technically accurate, "action" is more
intuitive as to what these unit plans typically are.
> Rename subdirectory "unit" to "action"

- plans/action/install.pp
Because we still want to install old versions of PE occasionally, it
seems.
> Re-add use of raw OIDs to csr_attribute.yaml files

- plans/action/install.pp
- tasks/submit_csr.json
- tasks/submit_csr.rb
So that Puppet 5 (PE 2018.1) can be supported.
> Make CSR submission version-aware

- plans/action/configure.pp
- tasks/read_file.json
- tasks/read_file.sh
Addresses https://github.com/puppetlabs/puppetlabs-peadm/issues/20
> configure classifier data in global hiera.yaml

- plans/upgrade.pp
- tasks/agent_upgrade.sh
- tasks/trusted_facts.json
- tasks/trusted_facts.rb
This PR makes the upgrade plan work at a base level with the current version of peadm.
> Modernize Upgrade Plan

- manifests/setup/node_manager.pp
Removed the hard fail for node manager.  It was causing a valid infrastructure (master with replica) to fail the task plan.   As best I can tell that hard fail isn't really necessary.
> Node manager fix

- functions/file_or_content.pp
- plans/action/install.pp
- plans/provision.pp
This commit allows you to manage the license key file
associated with PE.  This file is managed in the same
way the r10k private key file is currently managed in
this tool per the request of @reidmv
I did not create a type for the license key file as
Peadm::Pem was created for the content of the
r10k private key.  Please let me know if you feel
this is necessary.
> Manage license file

- plans/action/install.pp
We have observed setting r10k_private_key by default can cause conflicts with advanced code manager configuration keys passed in by pe_conf_data. To avoid the need to zero-out the r10k_private_key value, if the top-level r10k_private_key settings are not given to peadm::provision, do not set a pe.conf value for r10k_private_key.
> Eliminate default private key parameter value

- functions/file_or_content.pp
The function should be able to evaluate inputs that are undef.  This update allows for that.
> Update function to accept either string or undef data type.

- manifests/setup/node_manager.pp
- plans/action/configure.pp
Discovered a use case where compiler group B was not being created when the infrastructure did not have a puppetdb replica, but did have a master replica.  This caused compilers classified for cluster B to not be classified since the group did not exist.
This update addresses that.
> Node manager switch

- plans/action/install.pp
To support the use case wherein the certname of a system should be set to something besides the hostname (such as when the DNS A records are friendly names, but the system hostname(s) are not), do not leave certname settings up to Puppet's defaults.
Instead, at install time set the certnames of each server in the infrastructure to the target name of the server.
This will require a little bit of creative decision making with regards to the precheck validator, which used to insist that hostname == target name, and would fail if there was a mismatch.
> Set certnames to target names

- tasks/pe_install.sh
The peadm::pe_install task as written will probably never technically
fail, even when the puppet-enterprise-installer script exits non-zero.
This commit updates the task to exit with whatever exit code the
puppet-enterprise-installer script exited with. Not a perfect fix but a
step in the right direction.
Fixes #71
> Fail peadm::pe_install task when installer fails

- plans/upgrade.pp
Previously, when upgrading a standard architecture deployment, after the
master runs the puppet-enterprise-installer script auth for compilers
needs to be restored by a puppet agent run. However, the upgrade plan
only performed a run on the dedicated database host, which doesn't exist
in a standard install (the databases are all on the master).
This commit reworks the upgrade sequence such that the master and
replica recieve puppet runs at the appropriate points, along with the
database targets, to ensure that regardless of which node the
database(s) are located on the node will have a Puppet run to finalize
its config before upgrade moves on to the compilers.
Fixes #73
> Rework upgrade sequence to support Standard arch

- tasks/sign_csr.rb
- tasks/submit_csr.rb
* previously if the sign or request cert tasks were
run twice, the tasks would fail.  This adds idempotency
to the sign_csr and submit_csr tasks for puppet 6+ only.
> Make cert tasks more idempotent

- tasks/check_status.json
- tasks/check_status.sh
* It can be useful to get the status of a service or all the services
remotely from a information only purpose.  Additionally, this task
can also help plans figure out when a specific puppet service is
running correctly.  This greatly helps out when trying to determine
if a puppetserver is taking requests and not just running.
* This task uses the puppetserver status API endpoint
https://puppet.com/docs/puppetserver/latest/status-api/v1/services.html
> Add check status tasks

- plans/action/install.pp
* When the puppetserver has a high CPU usage normal tasks can often
take longer than anticipated.  If the puppetserver is not
ready for requests, the puppet runs will fail and the plan fails
shortly after.
This calls the check_status task to determine if the puppetserver
is not only up but taking requests. This will help prevent unwanted
failures. This code will sleep in 5 second increments up to a total
of 50 seconds.  If the puppetserver hasn't calmed down by then we
continue with the plan and let it fail during the puppet run.
> Add wait function during install

- plans/action/install.pp
* previously the install plan fails because the
insert_csr_extension was recently renamed and not updated.
Additionally, the parameter name changed and was also updated
in this commit which is required to complete the install.
Please verify the install.sh task usage is correct because I don't understand how it should be used.
> Fix incorrect task name in install plan

- manifests/setup/node_manager.pp
It appears that in a default install, the master is pinned to this
group.
> Pin master to PE Database group

- tasks/mv.json
- tasks/mv.sh
This task exists as a convenience for users who need predictable sudo
commands without variance to write into their sudoers rules. The only real
variable in commands used by peadm is the filename of the PE installer
tarball. This task can be used in a pre-plan to homogenize calls to sudo.
Rather than literally calling "mv" with a variable filename, the mv.sh task
can be called. Inputs come as environment variables so the call doesn't
change.
> Provide mv wrapper task

- README.md
This commit adds an explicit mention of where to get assistance with the
module. This commit also adds a link to the PE documentation as it now
features the three reference architectures.
> Add explicit help instructions to README

- tasks/download.sh
Prior to this commit, the `peadm::download` task would exit with
"success" when S3 returned a "404 Not Found" error page. This
would happen when a PE version was reqeusts that did not support
the OS platforms being provisioned. E.g. requesting an install of
PE 2018.1 on RedHat 8. The provisioning plan would then blow
later when `tar` found an XML document instead of a gzipped archive.
This commit updates the download task to:
- Print the URL being downloaded to stderr.
- Pass the `-f` flag to `curl` when downloading tarballs.
This causes curl to exit with a status of 22 if the
HTTP response is an error.
> Improve error handling of peadm::download task

- tasks/read_file.json
- tasks/read_file.sh
The commit that I am reverting causes hard failures in newly deployed infrastructure via https://github.com/puppetlabs/puppetlabs-autope on GCP with CentOS 7. My suspicion is the addition of `exit 1` upon detection that the file did exist, this fails the plan immediately but previously allowed to run to completion.
> Revert "made print() call Py3 compliant, added checks for Py execs"

- .sync.yml
- Gemfile
- README.md
- documentation/docker_examples.md
- spec/docker/Dockerfile
- spec/docker/Dockerfile_bolt
- spec/docker/extra-large-ha/docker-compose.yaml
- spec/docker/extra-large/docker-compose.yaml
- spec/docker/large-ha/docker-compose.yaml
- spec/docker/large/docker-compose.yaml
- spec/docker/standard-ha/docker-compose.yaml
- spec/docker/standard/docker-compose.yaml
- tasks/submit_csr.rb
These changes fix a a few minor annoyances I have found so far when operating the docker example containers. 
I also made some speed enhancements with the sign_csr.rb task so it would just load Puppet and use the settings instead of shelling out multiple times.
> Docker updates

- documentation/provision.md
- documentation/upgrade.md
- plans/action/install.pp
- plans/provision.pp
- plans/upgrade.pp
This commit adds a new download_mode parameter to the peadm::provision
and peadm::upgrade plans. The default value for the parameter is
bolthost, which causes PE installation content to be downloaded to the
stagingdir of the workstation running bolt and then uploaded to the
PE hosts. Setting download_mode to direct causes PE installation content
to be downloaded directly to the PE hosts. The direct mode skips uploads,
which offers a significant speed boost when the PE hosts have a route to
the internet and the bolt host is connected by a slow link, such as VPN.
> Add direct download option for PE installers

- plans/action/install.pp
puppet-enterprise-installer sets ownership to pe-puppet and mode to 0600 for the r10k private key, but does not manage the license key
change permissions, so pe-puppet can access license key during catalog compilation
> #106 fix permissions on the key files

- README.md
We need to enable the support team more before we can put their name in the README.
> Remove support team responsibilities in README

- .fixtures.yml
- CHANGELOG.md
- metadata.json
* The bolt gem does ship with the service module and the upgrade
plan requires the service module to be present.  If the user is
using the bolt package, the service module ships with it already
and so does the official docker image.
* This adds the service module as a requirement to metadata and
to fixtures.
> Add service module

- manifests/setup/node_manager.pp
Set ha_enabled_replicas to an empty array for compilers only. We are already supplying the specific certnames that compilers' PuppetDB terminus configuration should use.
Fixes #118
> Set ha_enabled_replicas to an empty array for compilers

- CHANGELOG.md
- manifests/setup/node_manager.pp
- plans/action/configure.pp
- plans/provision.pp
- plans/upgrade.pp
These are necessary to fully configure large and extra large architectures.
> Add compiler_pool_{a,b}_address parameters

- CHANGELOG.md
- tasks/puppet_infra_upgrade.json
- tasks/puppet_infra_upgrade.rb
Previously, it was observed several times that nodes might be in a state of disconnection from the orchestrator when peadm tries to perform a `puppet infra upgrade` operation. This commit implements a wait function to ensure that all nodes are orchestrator-connected before beginning a puppet infra upgrade operation.
> Wait until nodes connected before infra upgrade

- CHANGELOG.md
- plans/upgrade.pp
To make it easier to understand when different parts of the plan have been run, and completed successfully
> Add informational messages to upgrade plan

- CHANGELOG.md
- functions/oid.pp
- manifests/setup/convert_pre20197.pp
- plans/convert.pp
Previously, the user would need to specify the `configure_node_groups`
parameter when running the convert plan. In some circumstances failing
to pass the right value would break the convert operation.
This commit adds computed default values for this parameter so that the
user does not need to pass it.
> Eliminate convert configure_node_groups param

- plans/convert.pp
- plans/util/add_cert_extensions.pp
Two things.
1. Stop the puppet agent _before_ writing the csr_attributes.yaml file. This is to avoid a situation where the Puppet agent might delete or alter the file before a cert request is made.
2. Check for either the peadm availability group OID, OR use of the pp_cluster OID to identify nodes in A and B availability groups before falling back to simple even/odd indexing.
> Bug fixes to convert

- README.md
This commit provides an outline in the README for what the support process for the peadm module should be.
> Add support clause and instructions to README

- CHANGELOG.md
- plans/convert.pp
- plans/util/add_cert_extensions.pp
Basically, don't do work that isn't necessary. This commit changes how shortname/OID conflicts are handled for the pp_auth_role extension by just standardizing on always specifying OID, for now.
> Don't re-issue certs if they have required exts

- CHANGELOG.md
- lib/puppet/functions/peadm/merge_ng_config_data.rb
- manifests/setup/node_manager.pp
- metadata.json
Users may have their own config data specified for the PE Master group.
This commit ensures that when peadm enforces node group configuration
including config data on the PE Master group, it merges required config
into existing user data to avoid configuration loss.
Fixes #130
> GH-130 Fix overwrite of user config data

- tasks/puppet_runonce.sh
If a Puppet agent run is unable to complete cleanly, that should be reported as a problem so the plan(s) can stop or deal with it.
> Make puppet_runonce exit non-zero on resrc failure

- CHANGELOG.md
- types/singletargetspec.pp
For more than a year this type has included in its definition a
reference to Boltlib::SingleTargetSpec. That type doesn't exist; this
should have been a recursive reference to Peadm::SingleTargetSpec this
whole time. Not sure why it ever worked.
> Fix a problem with Peadm::SingleTargetSpec

- .sync.yml
- CHANGELOG.md
- metadata.json
- spec/spec_helper.rb
- spec/spec_helper_local.rb
- spec/unit/task/puppet_infra_upgrade_spec.rb
- tasks/puppet_infra_upgrade.rb
Catch exit code 11, indicating PuppetDB is not fully synced, but the replica is otherwise ready to go.
In order to boost confidence that this is working correctly, the puppet_infra_upgrade task has been refactored to support unit testing, and unit tests have been added.
> Infra upgrade improvement

- functions/check_bolt_version.pp
- lib/puppet/functions/peadm/bolt_version.rb
- plans/convert.pp
- plans/provision.pp
- plans/status.pp
- plans/upgrade.pp
- spec/functions/bolt_version_spec.rb
- added the function `bolt_version` returning the current Bolt version
- added the function `check_bolt_version` comparing the current Bolt version with the one supported by peadm
- added the call to `check_bolt_version` to all plans
> Add bolt_version function and use it in plans

- functions/validate_version.pp
- spec/functions/validate_version_spec.rb
* Previously there was not any unit tests for
validate_version function.  Additionally, the function
was updated to return a Boolean unless the unsupported
version is identified.  This return value, while not used
in plans helps with unit testing.
> Adds testing for validate_version

- plans/action/install.pp
bolt 2.44.0 started to emit warnings:
```
The documented parameter 'r10k_private_key' does not exist in plan signature [ID: missing_plan_parameter]
The documented parameter 'license_key' does not exist in plan signature [ID: missing_plan_parameter]
```
> fix documented parameters for peadm::install plan

- tasks/pe_install.sh
This prevent the following installation error when the source Bolt host runs a non-US locale:
`failed to call refresh: invalid byte sequence in US-ASCII`
> Ensure locales are set to en_US.UTF-8 for install

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitignore
- .gitlab-ci.yml
- .pdkignore
- .rubocop.yml
- .sync.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- README.md
- Rakefile
- appveyor.yml
- functions/check_bolt_version.pp
- functions/validate_version.pp
- lib/puppet/functions/peadm/bolt_version.rb
- metadata.json
- spec/functions/bolt_version_spec.rb
- spec/functions/validate_version_spec.rb
- spec/plans/status_spec.rb
- spec/spec_helper_local.rb
- spec/unit/task/puppet_infra_upgrade_spec.rb
- tasks/puppet_infra_upgrade.rb
Tested using peadm and Bolt 3.0.1 to deploy a new 2021 stack, as well as upgrade a 2019.8.5 stack to 2021.0. This PR modifies the version validation functions to indicate support for PE 2021.0, Bolt 3.x, and updates the PDK template to 2.0.0.
> PE 2021.0 support

- CHANGELOG.md
- README.md
- plans/action/install.pp
- plans/provision.pp
- spec/docker/extra-large-ha/params.json
- spec/docker/extra-large-ha/upgrade_params.json
- spec/docker/extra-large/params.json
- spec/docker/extra-large/upgrade_params.json
- spec/docker/large-ha/params.json
- spec/docker/large-ha/upgrade_params.json
- spec/docker/large/params.json
- spec/docker/large/upgrade_params.json
- spec/docker/standard-ha/params.json
- spec/docker/standard-ha/upgrade_params.json
- spec/docker/standard/params.json
- spec/docker/standard/upgrade_params.json
- tasks/pe_install.json
- tasks/pe_install.sh
- tasks/sign_csr.rb
This PR cleans up exit code handling when dealing with the fact that puppet-enterprise-installer exits 1 during extra-large installs, due to PuppetDB not being able to start yet.
> Fix installer exit handling

- plans/add_compiler.pp
- plans/util/insert_csr_extension_requests.pp
> SOLARCH-463-peadm-plan-add-or-replace-compiler

- plans/install.pp
- plans/subplans/configure.pp
- plans/subplans/install.pp
- spec/plans/install_spec.rb
- spec/plans/subplans/configure_spec.rb
- spec/plans/subplans/install_spec.rb
Establishing a pattern wherein plans which are really intended to be
pieces of other plans, rather than directly invoked by the user, are
located in the subplans directory. Having a separate "action" directory
for the subplans of peadm::install adds confusion, so it is being
consolidated.
> Move plans/action/* to plans/subplans/*

- .github/workflows/test-add-replica.yaml
- functions/get_targets.pp
- plans/add_replica.pp
- spec/fixtures/modules/peadm_spec/plans/add_replica.pp
- spec/functions/get_targets_spec.rb
- spec/plans/add_replica_spec.rb
> Add add_replica plan

- .github/workflows/test-add-replica.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- functions/assert_supported_pe_version.pp
- spec/functions/assert_supported_pe_version_spec.rb
Sets the upper bound for supported PE to something that matches a
released version of 2021.
> Support latest PE release

- plans/add_compiler.pp
Ensure on agent install that the agent is not running. This makes the
rest of the plan more durable, since unexpected agent runs won't
interrupt what we're doing.
> Improve predictability of peadm::add_compiler

- README.md
See https://tickets.puppetlabs.com/browse/FORGE-267 for more information.
> Use absolute links so they render properly on the Forge

- spec/plans/add_replica_spec.rb
- spec/plans/subplans/configure_spec.rb
- spec/plans/subplans/install_spec.rb
- spec/plans/upgrade_spec.rb
We want our spec tests to focus on testing logic, not just enumerating
which plans/tasks/commands are called. A big value out of these tests is
just making sure they run to completion logically, assuming each of the
tasks/plans doesn't fail.
This commit simplifies the spec tests to allow execution actions by
default, to achieve the value of making sure the plans run to completion
with as little cognative overhead or unnecessary repetition as possible.
> Use `allow_any_<action>` syntax to simplify specs

- plans/add_compiler.pp
- plans/convert.pp
- plans/modify_cert_extensions.pp
- plans/modify_certificate.pp
- plans/subplans/modify_certificate.pp
- plans/upgrade.pp
- spec/fixtures/plans/trusted_facts.json
- spec/plans/add_compiler_spec.rb
- spec/plans/convert_spec.rb
- spec/plans/modify_cert_extensions_spec.rb
- spec/plans/modify_certificate_spec.rb
- spec/plans/subplans/modify_certificate_spec.rb
- spec/unit/task/submit_csr_spec.rb
- tasks/cert_data.rb
- tasks/submit_csr.json
- tasks/submit_csr.rb
This PR replaces the old `peadm::modify_cert_extensions` plan with the `peadm::modify_certificate` plan. This plan supports setting DNS alt names, in addition to adjusting other extensions. It's also just a more friendly name.
> Replace plan peadm::modify_cert_extensions with peadm::modify_certificate

- examples/load_balancer.pp
It is not functional, but still useful as guidance for creating real
content.
> Move load_balancer class to examples

- manifests/setup/node_manager.pp
- tasks/get_peadm_config.json
- tasks/get_peadm_config.rb
This task can introspect an existing cluster (when run on a primary node) and return information about how the cluster is currently configured. In the future, this can be used to aid in running plans that need to modify the cluster, by reducing the amount of information the user must supply. For example, the add\_compiler plan, or (future) add\_postgresql. 
The task returns data about the cluster in both primary/replica form, as well as A/B form, since different forms are useful in different scenarios.
> Add get_peadm_config task

- plans/misc/divert_code_manager.pp
- plans/modify_cert_extensions.pp
- plans/subplans/configure.pp
- plans/subplans/install.pp
- plans/subplans/modify_certificate.pp
- plans/util/insert_csr_extension_requests.pp
- plans/util/retrieve_and_upload.pp
- plans/util/sanitize_pg_pe_conf.pp
Many plans in this module are not intended to be run directly, and are
instead subplans or utility plans for internal use. This commit updates
the doc comments in the plans to indicate to Bolt that they should not
be shown or displayed when running commands like `bolt plan show`.
> Highlight user-facing plans by hiding internal plans from bolt plan show output

- tasks/puppet_runonce.sh
- Do not use color codes, as this makes the output difficult to read
when returned by Bolt.
- Do not print \<space\>\<newline\>, since this combination will prevent
Ruby's yaml emitter from using the block form (which is easier to read
when newlines are involved). This doesn't have an immediate impact
since we will be seeing the error in JSON, probably, but it
potentially heads off confusion in the future if we choose to emit
yaml instead.
> Clean up output of puppet_runonce task

- tasks/enable_replica.sh
- tasks/provision_replica.sh
- tasks/puppet_infra_upgrade.rb
Same rationale as before: easier to read, cleaner output when viewed
coming back from Bolt. The color codes make it harder to read in JSON or
YAML documents.
> Add --color=false to other puppet commands

- tasks/puppet_infra_upgrade.rb
Previously if a token file contained a newline, the upgrade plan would fail. This commit fixes that bug. Token files ending with a newline will not cause an error.
> Fix upgrade bug for token files with newlines

- functions/generate_pe_conf.pp
A long time ago these settings were added to faciliate local development
on VirtualBox, using developer workstations. We should not provide
different memory defaults for PE installs than what is provided by PE
itself.
Additional fix: found Puppet Strings bug which prevented generating a
REFERENCE.md file. It is now possible to use Puppet Strings to generate
a REFERENCE.md.
> Remove hardcoded mem settings from default pe.conf

- plans/upgrade.pp
- spec/fixtures/plans/trusted-compiler.json
- spec/fixtures/plans/trusted-primary.json
- spec/plans/upgrade_spec.rb
Dan found this bug and commented in Slack. The new test shows the failing situation. The proposed fix is in this draft PR.
> Fix upgrade without replica

- tasks/code_sync_status.json
- tasks/code_sync_status.rb
This task runs and produces output based on the debug status on the primary server example output below
```{
"in_sync" : true,
"production" : {
"in_sync" : true,
"latest_commit" : "0ea2d64f8ac3db2d1e4bb0c1ce4e8d93735f46ea",
"pe-server-davidsand-0-d43377.h1bgkrbmw3xu5mervr4yvrwrba.xx.internal.cloudapp.net" : {
"sync" : true,
"commit" : "0ea2d64f8ac3db2d1e4bb0c1ce4e8d93735f46ea"
},
"pe-compiler-davidsand-0-d43377.h1bgkrbmw3xu5mervr4yvrwrba.xx.internal.cloudapp.net" : {
"sync" : true,
"commit" : "0ea2d64f8ac3db2d1e4bb0c1ce4e8d93735f46ea"
},
"pe-compiler-davidsand-1-d43377.h1bgkrbmw3xu5mervr4yvrwrba.xx.internal.cloudapp.net" : {
"sync" : true,
"commit" : "0ea2d64f8ac3db2d1e4bb0c1ce4e8d93735f46ea"
},
"pe-server-davidsand-0-d43377.h1bgkrbmw3xu5mervr4yvrwrba.xx.internal.cloudapp.net-orchestrator" …
```
> SOLARCH-558 code sync status task

- plans/subplans/install.pp
- tasks/download.json
- tasks/download.sh
The download task now accepts an extra parameter "check_download" and if set to true, downloads the signature file and checks the downloaded tarball against the signature. It requires the gpg binary to be installed on the download host.
> Add PE download signature checking

- .github/workflows/test-add-replica.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- README.md
- functions/assert_supported_bolt_version.pp
- functions/assert_supported_pe_version.pp
This commit updates CI defaults and supported version assertions to
indicate that PE 2021.3 is supported, and tested.
> Support PE 2021.3

- Gemfile
- plans/add_compiler.pp
- plans/add_replica.pp
- plans/misc/divert_code_manager.pp
- plans/modify_cert_extensions.pp
- plans/subplans/configure.pp
- plans/subplans/install.pp
- plans/subplans/modify_certificate.pp
- plans/util/insert_csr_extension_requests.pp
- plans/util/retrieve_and_upload.pp
- plans/util/sanitize_pg_pe_conf.pp
These are deprecated, replaced by `@api private`.
Also update Bolt gem dependency version requirement.
> Remove deprecated `# @private true` lines

- functions/certname.pp
- plans/upgrade.pp
- spec/functions/certname_spec.rb
When you use Target-type keys in a hash, it breaks the ability of the
plan to call an apply() block in Bolt <= 3.17.0. Not sure if this will
ever be fixed. Using the peadm::certname function on a target as a key
isn't perfect, because we don't have a hard guarantee that all hosts
have unique certnames, but it works better than Target for now. And if
hosts don't have unique certnames, lots more will break besides this.
> Use string keys for hash, instead of Target

- tasks/download.json
- tasks/download.sh
Iterating on this task to ensure it behaves well in an air-gapped
environment by default.
* Start by downloading the .asc file, always. If we don't re-download
that file, we aren't really verifying anything.
* Use the .asc file to try and verify existing content. Distinguish
between service-not-available (such as gpg not present, or unable to
reach keyserver) and verification failure.
* If unable to retrieve the .asc file, or if service-not-available,
fall back to size-verification.
* Parameterize the key ID and key server values, to keep the download
task plausibly generic, and not just for downloading the PE tarball.
> Improve download task gpg verification

- README.md
Commit updates language in the README to reflect that the module is now
supported under a Puppet Enterprise support contract. Leaves in language
informing users that it is intended as a services-led tool and advises
against adoption without comprehensive understanding about how it works.
> Make PEAdm a Puppet supported module

- documentation/install.md
> Update documentation to reference supported PE version

- tasks/download.sh
This fix makes it so that when files are downloaded, they are first downloaded to a temp file and moved into place only if the download completes and is successful. This avoids a scenario where a file can be partially downloaded, after which PEAdm thinks that the file is present and will attempt to use the partial file as-is, rather than re-downloading.
There are still ways that an incorrect file can end up being placed—namely, the download server returning HTTP 200 but the wrong file. This fix though should eliminate the problem caused by partial interrupted downloads.
* I'm validating whether `curl` successfully downloaded the file so we can throw an error
> Improve reliability of downloading PE tarball

- functions/assert_supported_pe_version.pp
- plans/install.pp
- plans/subplans/install.pp
- plans/upgrade.pp
- spec/functions/assert_supported_pe_version_spec.rb
Prior to this PR, there was no way to force an override to the PE version assertion. This PR adds a new parameter that will override the PE version check and output a warning when enabled. This is useful in testing new PE versions that are not yet supported by the module.
Note that the installation plan will emit two copies of the warning due to the function call in the `install` and `subplan::install` plans. I did not correct this as it seems acceptable to emit the warning multiple times.
```
Starting: plan peadm::install
WARNING: Permitting unsafe PE versions. This is not supported or tested.
Proceeding with this action could result in a broken PE Infrastructure.
WARNING: Permitting unsafe PE versions. This is not supported or tested.
Proceeding with this action could result in a broken …
```
> Add development and testing option to permit installing unsupported PE versions

- tasks/download.json
- tasks/download.sh
Rather than expecting that downloaded files will be signed with a known key, simply use the key from the signature asc file.
The purpose of this validation isn't to validate authenticity. It is only to validate digest. Because the packages we download have been signed with multiple different keys over the years, it isn't possible to anticipate a default key and expect it to work for all downloads.
Fixes #216
> Determine validation key from asc signature file

- tasks/download.sh
If moving the temporary file into the final location fails, make sure that error is caught and return values set appropriately.
> Catch mv errors when downloading

- metadata.json
- plans/install.pp
This ticket moves the default version of PE to the latest 2019.8.8 and allows puppetlabs/service module to 2.x support
2.x was about removing support for rhel/centos 5 and puppet 5
> SOLARCH-716 update pe version and supported puppetlabs/service module version

- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade.yaml
- README.md
- documentation/install.md
- functions/assert_supported_pe_version.pp
This commit adds support for PE 2021.4
> Support PE 2021.4

- plans/backup.pp
- spec/plans/backup_spec.rb
The rest can be auto-determined.
Also move all validation code as high up as possible, to enable maximum fail-fast semantics.
> Only require primary host param for backup

- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade.yaml
- README.md
- documentation/install.md
- functions/assert_supported_pe_version.pp
Modify assert_supported_pe_version function, README, and CI matrices
> Add support for PE 2021.5

- plans/install.pp
- plans/subplans/install.pp
- plans/upgrade.pp
- spec/plans/subplans/install_spec.rb
- types/pe_version.pp
All PE version downloads need to match the x.y.z format. This commit
changes the type specifier to require this format.
This is especially useful to help guide people to the right parameters
if they specify a version like "2022.4" instead of "2022.4.0".
> Make versions match SemVer pattern

- tasks/get_peadm_config.rb
The "A" group is configured to use the "B" compiler lb; the logic didn't reflect this, and assumed the configured compiler on the "A" group was the "A" compiler - which doesn't make sense.
This commit fixes the incidental swap.
> Fix LB swap bug in get_peadm_config task

- plans/util/code_sync_status.pp
- tasks/code_sync_status.rb
Just a draft to save some doodling. The JSON from the task is not the easiest to read, compared to output such as the following.
```
Starting: plan peadm::util::code_sync_status
Starting: task peadm::code_sync_status on pe-server-37cf31-0.us-west1-a.c.puppet-solutions-architects.internal
Finished: task peadm::code_sync_status with 0 failures in 4.49 sec
+--------------------------------+------+
|                Summary                |
+--------------------------------+------+
| Overall sync status            | true |
| production environment in sync | true |
+--------------------------------+------+
+-----------------------------------------------------------------------------------+---------+---------------------------------------------+
| …
```
> Create sample plan to display code sync status

- metadata.json
- tasks/precheck.sh
Prior to this commit when run against a SLES platform, peadm::download would assume the platform was EL based and form a url that was the SLES version number with the EL os family, and ultimately Fail.
This commit adds logic to detect SLES, it leaves EL detection in an "else" catch all, but this is only problematic if the plan is run against an unsupported Primary OS Family, and maintains existing behavior.
this commit is brought to you by "works for me" level testing, in that i have successfully spun up Stadard EL   / sles / and Ubuntu environments with this modification
> Add SLES Support to pre_check task

- files/task_helper.sh
A few missing /g instructions prevented successful complete string
escapes. This adds the missing /g directives.
> Fix json escaping in bash task-helper

- documentation/automated_recovery.md
- plans/util/update_classification.pp
Provides documentation for the automated recovery of a failed
PE-PostgreSQL node in a XL with replica architecture
> (SOLARCH-434) Procedure for recovering PSQL

- plans/add_compiler.pp
This commit adds a file_line resource which will configure a
pe-puppetdb-pe-puppetdb-read-map in pg_ident.conf so that the PuppetDB
instance which is setup on new compilers using the add_compiler plan
will start properly.
> Add read map so puppetdb can start on new compiler

- documentation/convert.md
- documentation/upgrade.md
Just a cosmetic thing, switching the Plan name from provision to install in the convert and upgrade documentation
----
Related PR: https://github.com/puppetlabs/puppetlabs-peadm/commit/631b94aac3028c37ee1922660a7e783cf8c42cd3
> Fix docs references from "provision" to "install"

- plans/install.pp
- plans/subplans/install.pp
- plans/upgrade.pp
This new parameter to peadm::install and peadm::upgrade allows users to manually specify where to download the PE installer tarball from.
> Add optional `pe_installer_source` parameter

- .fixtures.yml
- .vscode/settings.json
- Gemfile
- documentation/automated_recovery.md
- metadata.json
- plans/add_database.pp
- plans/add_replica.pp
- plans/subplans/component_install.pp
- plans/subplans/modify_certificate.pp
- plans/subplans/prepare_agent.pp
- plans/util/sync_global_hiera.pp
- plans/util/update_classification.pp
- plans/util/update_db_setting.pp
- spec/plans/add_replica_spec.rb
- tasks/cert_valid_status.json
- tasks/cert_valid_status.rb
Ensure classification is updated appropriately. Lacking classification results in plans only being able to replace components if they are of the same name but entirely unconfigured.
> Fix classification when adding some components

- plans/add_compiler.pp
- spec/plans/add_compiler_spec.rb
Fix that ensures compiler is functional when deployed using `add_compiler` and a replica server is present
> Set additional rules on replica when adding compiler

- plans/convert.pp
Restarts compiler services on infrastructure nodes which are unlikely to
have them restarted by final Puppet run.
> Restart compiler services

- documentation/automated_recovery.md
- plans/add_replica.pp
Includes instructions for conducting automated recovery of a peadm deployed cluster. Includes small change to `add_replica` to facilitate documented workflow.
> Updates documentation

- plans/subplans/configure.pp
Fixes unnoticed items that were missed in the usage of copy_file
> Fix-ups in copy_file plan usage

- tasks/precheck.sh
Commit fixes failures which occur in some Bolt operating scenarios when OS is a RedHat derivative and commands for enabling fips are missing.
> Ensure fips commands exists before using it

- README.md
- documentation/expanding.md
Commit creates documentation/expansion.md which explains how to use the add_compiler, add_database, and add_replica to expand your PE deployment, converting to a new architecture, adding disaster recovery, or increasing compilation capacity
> Provide documentation on expanding a deployment

- .github/workflows/test-upgrade-matrix.yaml
Renames the existing test-upgrade.yaml to test-upgrade-matrix.yaml and create new test-upgrade.yaml which uses workflow_dispatch for manual invocation.
This is the same structure used for providing install tests.
> Provide automated and on-demand upgrade test

- plans/install.pp
- plans/subplans/configure.pp
Provides a parameter in plans peadm::install and peadm::subplans::configure which can be used to set the final state of the puppet agent which runs on infrastructure nodes. Allows for stopped or running states only.
> Parameter for setting final state of agents

- tasks/agent_install.json
- tasks/agent_install.ps1
- tasks/submit_csr.json
- tasks/submit_csr.ps1
This allows the creation of windows nodes as test clients via peadm
> Adding windows node capability

- tasks/precheck.sh
Prior to this commit, `peadm` used the `fips-mode-setup --is-enabled` command to detect whether FIPS mode was enabled. Unfortunately, this command does not produce a meaningful exit code. It exits with success on RHEL 8 where the `--is-enabled` flag is invalid:
```
$ fips-mode-setup --is-enabled
Check, enable, or disable the system FIPS mode.
usage: /usr/bin/fips-mode-setup --enable|--disable [--no-bootcfg]
usage: /usr/bin/fips-mode-setup --check
$ echo $?
0
```
And exits with success when FIPS mode is disabled:
```
$ fips-mode-setup --check
Installation of FIPS modules is not completed.
FIPS mode is disabled.
$ echo $?
0
```
The end result is that if the `crypto-policies-scripts` package happens to be installed on a RHEL node, `peadm` will assume the node is in FIPS mode and download the …
> Sync FIPS detection with the PE installer

- plans/convert.pp
Prior to this commit, the finalize step of `peadm::convert` would fail when operating on PE XL installations as the Primary Database and Replica Database nodes do not run the pe-puppetdb or pe-puppetserver services:
```
The command failed with exit code 5
STDERR:
Failed to restart pe-puppetserver.service: Unit not found.
Failed to restart pe-puppetdb.service: Unit not found.
```
This commit updates the convert plan to exclude the database nodes from that service restart.
> Fix XL failures in finalize step of peadm::convert

- .github/workflows/release-prep.yml
- .github/workflows/release.yml
- .sync.yml
Currently our prep image was set to an old IAC image instead of a set PDK image for our supported version and our publish was set to latest instead of what PDK version our module is using. I have set both to be correct version
@binford2k @mcka1n this is some process and knowledge work I think we need to look at
> Updating github workflow release images

- .sync.yml
Locking changelog_generator version due to dropped support with ruby 2 in 1.16
> Locking changelog_generator gem version

- REFERENCE.md
- functions/fail_on_transport.pp
- plans/subplans/modify_certificate.pp
- plans/upgrade.pp
- plans/util/retrieve_and_upload.pp
- spec/functions/fail_on_transport_spec.rb
- spec/plans/subplans/modify_certificate_spec.rb
- spec/plans/upgrade_spec.rb
- spec/plans/util/retrieve_and_upload_spec.rb
This changeset updates `peadm::util::retrieve_and_upload` to fail if the PCP transport is in use. When PCP is in use, file uploads are done via the `bolt_shim::upload` task, which essentially reads the file into memory, encodes it, and then ships it over Orchestrator as an argument to the `bolt_shim::upload` task.
This method of file transfer is utterly inadequate for shipping files as large as the PE installer.
Additionally, the `fail_on_transport()` function is enhanced to accept an optional error message and existing usages of `fail_on_transport()` are updated with descriptive messages that explain why PCP is unavailable and how to work around it.
Unit tests for `fail_on_transport()` are also fully implemented.
> Fail with guidance if peadm::util::retrieve_and_upload is used on PE XL with the PCP transport

- plans/subplans/db_populate.pp
I have bolt 3.26.2 and puppet 7.21.0
Both `puppet parser validate` and `bolt module install` complain about syntax error
```
Error: Could not parse for environment production: Syntax error at '}' (file: puppetlabs-peadm/plans/subplans/db_populate.pp, line: 69, column: 30)
```
If I remove braces on that line error advances to next line with the same issue, so I removed them all
> fix variable notation

- plans/subplans/configure.pp
- plans/upgrade.pp
Previously similar parameter was add to install/configure plans to accommodate necessary customizations
> add parameter for setting final state of infrastructure agents after upgrade

- .github/workflows/auto_release.yml
- .sync.yml
Prior to this commit the base PDK docker image was being used, this container did not have any build tools present, so any gem that required building dependencies would cause validation checks to fail
Updated to dev-tools-container which is maintained by product, this has the required dev tools, this allows us to update to the latest change log generator gem, which has many bug fixes
> switch to dev tools container and update changelog generator

- plans/install.pp
- plans/subplans/install.pp
- spec/acceptance/peadm_spec/plans/install_test_cluster.pp
When using the module in workflows for testing the install_test_cluster plan is called. This PR adds the ability to pass the param code_manager_auto_configure to the plan and set it to false. It should still be set to true by default if nothing is passed. 
Setting it to true was causing issues with installing modules for testing.
> Allow code manager auto configure to be passed as param

- plans/add_database.pp
- plans/status.pp
When a database is added outside of the peadm::install plan, the /etc/puppetlabs/enterprise/conf.d/ directory structure is not created. When the peadm::upgrade plan is run, it fails because it can't write the pe.conf file because the directory doesn't exist. The contents of the file aren't that important, they get rewritten when the upgrade runs. This change just ensures the directory is there for it.
> Adding /etc/puppetlabs/enterprise/conf.d/pe.conf

- documentation/upgrade.md
Documentation update: added note for offline/airgapped upgrades for environments with `pe_repo` classes for different agent platforms
In offline/airgapped environments, the agent repo tarballs need to be staged before the `peadm::upgrade` plan is run, otherwise the plan will fail when it does the puppet run to complete the upgrade.
Thanks @sooyean-hoo for noting this during recent PS engagement.
> Documentation update for offline upgrades

- tasks/transform_classification_groups.py
Fixes a tiny typo in the inline documentation
> transform_classification_groups.py: fix typo

- .github/workflows/auto_release.yml
- .github/workflows/spec.yml
- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-latest-dev.yaml
- .github/workflows/test-install-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
Removed HoneyComb from each of the Github Actions workflows, as we are not using it in our modules any longer.
> (PE-35899) Remove HoneyComb from the PEADM Github Actions

- .github/workflows/test-install-latest-xlarge-dev-nightly.yaml
- functions/determine_status.pp
- functions/generate_pe_conf.pp
- metadata.json
- plans/add_database.pp
- plans/status.pp
- plans/subplans/install.pp
- plans/upgrade.pp
- plans/util/insert_csr_extension_requests.pp
As stdlib had updated, some methods that we are using had been deprecated. I've updated to_json_pretty, merge, to_yaml, parsehocon as well as adjusted the metadata to include Puppet8 meaning that it will now be included in the test matrix.
> (PE-36172) Fixing issues related to stdlib changes

- .github/workflows/spec.yml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-upgrade-matrix.yaml
As the title says, we only need to run our tests only when code is changed in the repo. Hence, I added all the paths that have code files in them to be checked on pull_requests.
> (PE-35908) Optimize the full CI test to only trigger on code

- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-upgrade-matrix.yaml
CI was triggering both on open and review request when you were creating a PR
> (MAINT) Stop CI from triggering twice

- metadata.json
We need to bump inifile so it will use latest stdlib
>  (#366) Bump inifile and stdlib

- metadata.json
https://github.com/puppetlabs/puppetlabs-peadm/commit/8016fbea77e32255b3ff89d80f38e82e3b72e8d2 introduced a few functions calls that are only available in stdlib 9 and newer.
> puppetlabs/stdlib: Require 9.x

- tasks/download.json
security teams frequently overlook allowing the standard pgpkeyserver port
fortunately the ubuntu keyserver also responds on port 80
> keyserver port 80 less likely to be blocked

- REFERENCE.md
- plans/install.pp
- plans/subplans/install.pp
- spec/plans/subplans/install_spec.rb
- types/known_hosts.pp
Starting with PE 2023.3, updates to r10k libraries from PE-35980 changes in libgit2 now verify host keys. Because of this code manager now needs to be configured with known hosts public key information for the r10k remote host. Without this, PE will install but code manager will fail to deploy.
~~This patch will fail the plan early if installing PE 2023.3+, with r10k_private_key (so using ssh protocol) and no r10k_known_hosts array.~~
* https://perforce.atlassian.net/browse/PE-36579
* https://perforce.atlassian.net/browse/PE-36580
* https://perforce.atlassian.net/browse/PE-35980
> (PE-36580) Add r10k_known_hosts to install plan

- REFERENCE.md
- documentation/upgrade.md
- examples/upgrade.json
- functions/check_version_and_known_hosts.pp
- functions/get_pe_conf.pp
- functions/update_pe_conf.pp
- plans/upgrade.pp
- spec/plans/upgrade_spec.rb
- types/known_hosts.pp
Adding optional parameter for r10k known hosts
Alerting user to set known hosts if they are upgrading to or past 2023.3
> (PE-36789) R10k Known hosts upgrade path

- .github/workflows/test-install-latest-dev.yaml
- .github/workflows/test-install-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
My old twingate PR for their GH action wasn't merged, so went and created a retry myself. I also raised a new pr (https://github.com/Twingate/github-action/pull/4) with them. In the meantime, we can use my fork.
Sometimes twingate isn't connected and because of lack of retry, fails CI.
Closing the old PR (https://github.com/puppetlabs/puppetlabs-peadm/pull/362) with me reverting to use twingate official action.
> (PE-36836) Twingate retry connection

- tasks/agent_install.sh
The install.bash script from PE supports agent updates and upgrades since a long time. I don't see a reason why the task in peadm should abort if it isn't a new installation. I understand if the support team doesn't want to take responsibility for upgrades/updates, but I think we shouldn't block users/SDP consultants using it.
> agent_install: Enable Agent upgrades

- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- README.md
- documentation/release_process.md
- documentation/upgrade.md
- functions/assert_supported_pe_version.pp
- spec/plans/subplans/install_spec.rb
> (PE-36943) Support version 2023.4

- plans/add_compiler.pp
- plans/subplans/component_install.pp
- plans/subplans/prepare_agent.pp
- spec/plans/add_compiler_spec.rb
The plan `peadm::add_compiler` has been updated to make use of the `peadm::subplans::component_install` so that it doesn't error when run over PCP transport.  This also makes the management of the agent installation consistent with `peadm::add_database` and `peadm::add_replica` plans.
In addition, updates were made to `peadm::subplans::component_install` as the trusted facts set for compilers are different to other Puppet infrastructure roles and updates were made to `peadm::subplan::agent_install` to add dns-alt-names to the certificate if provided. 
Closes #355
> Fix for plan peadm::add_compiler over pcp transport

- .github/workflows/mend.yml
Fixing the nightly and on demand vuln scan. Also run on a pr merge
Wasn't scanning at all
> (PE-36944) Changing when when CI mend will be triggered/executed

- plans/subplans/install.pp
We've logic in place that checks if the user provided an r10k remote key and then automatically enable code-manager. This doesn't make sense because the key is optional. We need to depend on a r10k URL. The URL can be an absolute path to a local repo or an https url, both don't require a remote key.
Fixes a bug I introcued in https://github.com/puppetlabs/puppetlabs-peadm/pull/352/files#r1373941616
> peadm::install: Depend code-manager setup on r10k remote presence, not r10k ssh key

- REFERENCE.md
- documentation/backup_restore_ca.md
- plans/backup_ca.pp
- plans/restore_ca.pp
- spec/plans/backup_ca_spec.rb
- spec/plans/restore_ca_spec.rb
Utilising puppet_backup for backing up and restoring CA and SSL certificates on a target
> (PE-35906) Adding plans for backing up and restoring CA

- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
- REFERENCE.md
- documentation/install.md
- plans/install.pp
- spec/functions/assert_supported_pe_version_spec.rb
- spec/plans/convert_spec.rb
- spec/plans/install_spec.rb
- spec/plans/upgrade_spec.rb
Updating default install version to 2021.7.6
Updating default from 2021.7.4 to 2021.7.6
Updated tests to match latest LTS version
> (PE-37192) Updating default install version to 2021.7.6

- REFERENCE.md
- tasks/puppet_runonce.json
- tasks/puppet_runonce.sh
During provisioning it can be necessary to run agents in a sanitized environment that will make production environment operational:
- install hiera gems
- install report processors
> add environment parameter to puppet_runonce task

- .fixtures.yml
[Jira ticket ](https://perforce.atlassian.net/browse/PE-37232)
Remove puppet debug as it is not currently being used in the PEADM repo. 
> (PE-37232) Remove puppet debug dependency

- README.md
Providing instructions on how to install the module. Removing instructions about using the install plan.
> Update README.md with steps to install the module

- metadata.json
- tasks/precheck.sh
PE supports AmazonLinux 2 but using the EL7 tarball. This adds the update to the pre-check to allow it to download that package.
Currently the pre-check returns el but value of 2 from the VERSION_ID and it needs to return 7 in order to download the appropriate package.
> Adding amazonlinux to pre-check

- REFERENCE.md
- tasks/puppet_runonce.json
- tasks/puppet_runonce.sh
> make configurable: timeout to wait for in-progress run

- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
- REFERENCE.md
- documentation/install.md
- documentation/upgrade.md
- functions/assert_supported_pe_version.pp
- plans/install.pp
- spec/functions/assert_supported_pe_version_spec.rb
- spec/plans/convert_spec.rb
- spec/plans/install_spec.rb
- spec/plans/upgrade_spec.rb
Update to 2023.6.0 support
Updating default install version to 2021.7.7
Updating default from 2021.7.6 to 2021.7.7
Updated tests to match latest LTS version
> (MAINT) Update PEADM with 2023.6 support

- Gemfile
release_prep gem group added to facilitate release prep github action for new module version release
> (MAINT) release_prep gem group added

- .github/workflows/ci.yml
- .github/workflows/module_ci.yml
- .github/workflows/nightly.yml
- metadata.json
This PR augments the previous one by pinning WhatsARanjit/node_manager to 0.7.5 in metadata.
Please note that PEADM needs to be released on the Forge for this update to take effect for users.
> Pin node_manager in metadata

- examples/provision/extra-large-ha.json
- examples/provision/extra-large.json
- examples/provision/large-ha.json
- examples/provision/large.json
- examples/provision/minimal.json
- examples/provision/standard-ha.json
- examples/provision/standard.json
- spec/acceptance/peadm_spec/plans/install_test_cluster.pp
- spec/docker/extra-large-ha/params.json
- spec/docker/extra-large/params.json
- spec/docker/large-ha/params.json
- spec/docker/large/params.json
- spec/docker/standard-ha/params.json
- spec/docker/standard/params.json
- spec/plans/install_spec.rb
- spec/plans/subplans/install_spec.rb
The new version of PE requires a 12 characters minimum password. 
CI is failing because we used a password with less than 12 characters
> (MAINT) CI fix, PE console requires a minimum password of 12 characters

- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install-rhel-9.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
- REFERENCE.md
- documentation/install.md
- documentation/upgrade.md
- functions/assert_supported_pe_version.pp
- plans/install.pp
- spec/functions/assert_supported_pe_version_spec.rb
- spec/plans/convert_spec.rb
- spec/plans/install_spec.rb
- spec/plans/upgrade_spec.rb
Update to 2023.7.0 support
Updating default install version to 2021.7.8
Updating default from 2021.7.7 to 2021.7.8
Updated tests to match latest LTS version
> (MAINT) Update PEADM with 2023.7.0 support

- .github/workflows/test-add-compiler-matrix.yml
- spec/acceptance/peadm_spec/plans/add_compiler.pp
- spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
Updated add_compiler spec to check compiler has been added and puppet run before running add compiler
Added test matrix for add compiler
> (PE-37233) Adding add_compiler to test matrix

- README.md
JIRA - https://perforce.atlassian.net/browse/PE-38490
Clarifying that PEADM can install PE only on the operating systems supported for specific PE versions. Users should refer to the PE documentation for the version they want to install.
> PE-38490 Update README.md

- .github/workflows/test-upgrade-matrix.yaml
- plans/upgrade.pp
Running into issue that not all services relating to Orchestrator are fully started after upgrade to 2023.7. ie pe-host-action-collector. This is then meaning that the upgrade of the other hosts cant be completed.
Added 2023 to upgrade matrix. Including 2021 to 2023, excluding 2021 to 2021 and 2019 to 2023
> (PE-38736) Adding puppet run after primary upgrade

- .github/dependabot.yml
That will enable Dependabot updates. It will check for used GitHub Actions and provide a PR when one of the actions is outdated.
> Dependabot: check for outdated GitHub Actions

- .fixtures.yml
Without this, we get the following warning during the spec_prep rake task:
```
warning: redirecting to https://gitlab.com/nwops/bolt-container_inventory.git/
```
> .fixtures.yml: Fix URL for bolt-container_inventory

- .github/workflows/test-upgrade-legacy.yaml
- REFERENCE.md
- documentation/convert.md
- documentation/upgrade_with_legacy_compilers.md
- functions/oid.pp
- manifests/setup/legacy_compiler_group.pp
- manifests/setup/node_manager.pp
- plans/convert_compiler_to_legacy.pp
- plans/subplans/component_install.pp
- plans/subplans/install.pp
- plans/update_compiler_extensions.pp
- plans/upgrade.pp
- spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
Added plans to add legacy compiler param to certs, and other plan for creating legacy compiler groups and setting the legacy param to true.
This then allows compilers to be setup without puppetdb.
> Adding support for legacy compilers

- REFERENCE.md
- manifests/setup/legacy_compiler_group.pp
- manifests/setup/node_manager.pp
- tasks/classify_compilers.json
- tasks/classify_compilers.rb
Task added to classify a list of compilers as legacy or non legacy
Example usage:
`bolt task run peadm::classify_compilers -t oncoming-ram.delivery.puppetlabs.net --params '{"compiler_hosts": ["ideal-lament.delivery.puppetlabs.net", "tool-propaganda.delivery.puppetlabs.net", "saner-daughter.delivery.puppetlabs.net", "kindly-intruder.delivery.puppetlabs.net", "murky-tombstone.delivery.puppetlabs.net"]}'`
> PE-38768 classify compilers task added

- .github/workflows/mend.yml
- Removed specific steps for setting up Ruby, Java, and running the scan
- Integrated shared tooling workflow from puppetlabs/cat-github-actions
- Inherited secrets and set environment variable for PRODUCT_NAME
> (MAINT) update mend workflow to use shared tooling

- REFERENCE.md
- plans/add_compiler.pp
- spec/plans/add_compiler_spec.rb
Making the following parameters optional:
- primary_postgresql_host, if not provided will be determined through get_peadm_config
- avail_group_letter, is defaulting to A
> (PE-38814) add_compiler - Making primary_postgresql_host and avail_group_letter optional

- REFERENCE.md
- documentation/install.md
- functions/assert_supported_architecture.pp
- plans/convert_compiler_to_legacy.pp
- plans/install.pp
- plans/subplans/configure.pp
- plans/subplans/install.pp
- spec/functions/assert_supported_architecture_spec.rb
- spec/plans/subplans/install_spec.rb
- Added `legacy_compilers` parameter to `peadm::install`, `peadm::subplans::install`, and `peadm::subplans::configure` plans.
- Updated `peadm::assert_supported_architecture` function to handle `legacy_compilers`.
- Modified various plans to include `legacy_compilers` in the installation and configuration processes.
- Updated documentation to reflect the changes and added examples for `legacy_compilers`.
This change allows the PEADM module to support legacy compilers in addition to the standard compilers.- Added `legacy_compilers` parameter to `peadm::install`, `peadm::subplans::install`, and `peadm::subplans::configure` plans.
- Updated `peadm::assert_supported_architecture` function to handle `legacy_compilers`.
- Modified various plans to include `legacy_compilers` in the installation …
> (PE-38770) Install Plan accepts legacy_compilers key

- REFERENCE.md
- documentation/convert.md
- plans/convert.pp
- Introduced `legacy_compilers` parameter to handle legacy compiler hosts.
- Added logic to filter and categorize legacy compiler targets.
- Updated certificate modification steps to include legacy compiler targets with appropriate extensions.
- Added a step to run puppet on all targets after restarting services.
- Ensures all targets are fully up-to-date after conversion.
- Added 'legacy_compilers' section in the example JSON parameters.
- Improved clarity in the description of the `begin_at_step` parameter.
- Fixed minor grammatical issues in the instructions for converting compilers to legacy.
> (PE-38771) Convert plan accepts legacy compilers key in params.json

- documentation/add_compiler.md
- documentation/expanding.md
- plans/add_compiler.pp
Adding new documentation page for the new add compiler plan
N/A
N/A
> (PE-37235) Verify and update documentation on add_compiler

- .github/workflows/test-add-replica-matrix.yaml
- .github/workflows/test-add-replica.yaml
- plans/add_replica.pp
- spec/acceptance/peadm_spec/plans/add_replica.pp
- spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
add_replica plan updated with correct certname passed to update_classification plan, test matrix added
> PE-38815 add_replica plan updated, test matrix added

- REFERENCE.md
- plans/add_replica.pp
Removing experimental and private from add_replica
Updated help string text
> (PE-38818) Removing experimental and private from add_replica

- REFERENCE.md
- functions/get_node_group_environment.pp
- manifests/setup/node_manager.pp
- plans/add_database.pp
- plans/add_replica.pp
- plans/convert.pp
- plans/install.pp
- plans/subplans/configure.pp
- plans/upgrade.pp
- plans/util/update_classification.pp
- spec/functions/get_node_group_environment_spec.rb
- spec/plans/convert_spec.rb
- spec/plans/install_spec.rb
- spec/plans/upgrade_spec.rb
This checks if a user configured a environment in pe.conf. If that's the case, it will be used for the PEADM-specific node groups. Otherwise we fall back to production.
This fixes a timing issue discovered in #469. In situations where the PE infra isn't running in production, we cannot assume that a production environment exists. And a node group can only reference classes from the environment the node group belongs to.
> (#469) Assign correct environment to node groups

- plans/convert.pp
- tasks/check_legacy_compilers.rb
- Introduced a new task `check_legacy_compilers.rb` to verify legacy compilers.
- Updated `convert.pp` to run the new task and display warnings if legacy compilers are detected.
> (PE-38769) Task/Plan to identify conflicting classifications on legacy compilers and warn the user

- documentation/add_replica.md
- documentation/expanding.md
> (PE-38817) Adding docs for add replica

- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install-rhel-9.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
- REFERENCE.md
- documentation/install.md
- documentation/upgrade.md
- functions/assert_supported_pe_version.pp
- plans/install.pp
- spec/functions/assert_supported_pe_version_spec.rb
- spec/plans/convert_spec.rb
- spec/plans/install_spec.rb
- spec/plans/upgrade_spec.rb
- Updated default PE version in various GitHub workflow YAML files.
- Updated example parameters in documentation files.
- Adjusted supported PE version range in assert_supported_pe_version function.
- Modified unit tests to reflect the new default PE version.
> (PE-39612) update default PE version to 2021.7.9 and 2023.8.0

- spec/acceptance/peadm_spec/plans/install_test_cluster.pp
CI jobs triggered from forked branches aren't able to access secrets. In this case we are using a randomised password.
> (PE-39224) Adding random console password for forked pr workflow

- .github/dependabot.yml
- .github/workflows/yamlformatter.yml
- changed_files.txt
> (MAINT) Fix for dependabot.yml and exclude it from yamlfix

- .github/workflows/test-add-replica-matrix.yaml
- .github/workflows/test-add-replica.yaml
- spec/acceptance/peadm_spec/plans/verify_replica.pp
Smoke test added to CI to verify presence of the newly added replica
> PE-39228 add_replica smoke test

- .github/workflows/test-add-replica-matrix.yaml
- .github/workflows/test-add-replica.yaml
- REFERENCE.md
- documentation/add_replica.md
- documentation/expanding.md
- plans/add_replica.pp
- spec/acceptance/peadm_spec/plans/add_replica.pp
- spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
- spec/acceptance/peadm_spec/plans/verify_replica.pp
Adding official support of add replica plan
> (PE-38815-18) Official support of Add replica plan

- REFERENCE.md
- plans/add_replica.pp
- spec/plans/add_replica_spec.rb
- tasks/code_manager_enabled.json
- tasks/code_manager_enabled.rb
When user tries to add replica without code manager setup they were getting an error without any descriptive message.
This is adding a check to add_replica to alert user to enable code manager before proceeding.
> (PE-39118) Adding code manager check to add_replica

- REFERENCE.md
- plans/add_replica.pp
- tasks/backup_classification.rb
- tasks/code_manager_enabled.json
- tasks/code_manager_enabled.rb
- tasks/code_sync_status.rb
- tasks/pe_ldap_config.rb
- tasks/puppet_infra_upgrade.rb
- tasks/restore_classification.rb
Fix AiTM attacks vulnerability.
> (ITHELP-98367) - Fix AiTM attacks vulnerability

- tasks/get_peadm_config.rb
- tasks/rbac_token.rb
- Changed SSL verification mode to VERIFY_PEER for enhanced security.
- Added Puppet settings initialization to load necessary certificates.
- Updated HTTP request to use Puppet's certname and certificate files.
- Ensured CA file is set for SSL verification.
> (MAINT) SSL Verification extended

- .github/workflows/test-legacy-compilers.yaml
- .github/workflows/test-legacy-upgrade.yaml
- spec/acceptance/peadm_spec/plans/add_inventory_hostnames.pp
- Install Puppet Enterprise with legacy compilers 
- Convert one compiler to legacy and verify the conversion
> (PE-39307) Legacy compilers support smoke tests

- documentation/convert.md
Updated the documentation to reflect the new version 3.25 for Puppet Enterprise installed with puppetlabs-peadm. This change ensures the documentation is accurate and up-to-date with the latest version.
> chore(docs): update version references for puppetlabs-peadm

- REFERENCE.md
- plans/convert.pp
- plans/upgrade.pp
- spec/plans/convert_spec.rb
- spec/plans/upgrade_spec.rb
- tasks/get_group_rules.json
- tasks/get_group_rules.rb
> PE-38801 Task added to fetch rules for PE Infrastructure Agent group and warn user that they will be replaced

- .github/workflows/test-legacy-upgrade.yaml
- Added a step to generate a random hash for the console password using /dev/urandom.
- Updated the params.json creation to use the generated hash instead of a fixed secret.
- Ensured the hash is printed for debugging purposes.## Summary
> feat(workflow): add random hash generation for console password in test-legacy-upgrade

- REFERENCE.md
- plans/upgrade.pp
- plans/util/retrieve_and_upload.pp
- tasks/puppet_infra_upgrade.rb
- tasks/validate_rbac_token.json
- tasks/validate_rbac_token.rb
The upgrade plan now checks if the token used to upgrade compilers is valid before beginning the upgrade process. This is accomplished using a validate_rbac_token task
Closes #340 
```
Starting: plan peadm::upgrade
Starting: task peadm::validate_rbac_token on direct-blitz.delivery.puppetlabs.net
Finished: task peadm::validate_rbac_token with 1 failure in 6.3 sec
Finished: plan peadm::upgrade in 6.46 sec
Failed on direct-blitz.delivery.puppetlabs.net:
The task failed with exit code 1
403 puppetlabs.rbac/token-revoked: 
Check your API token at /root/.puppetlabs/token. An alternate token file can be specified using the token_file param. 
See https://www.puppet.com/docs/pe/latest/rbac_token_auth_intro for more details. 
Failed on 1 target: direct-blitz.delivery.puppetlabs.net
```
> (PE-39411) Add descriptive error during infrastructure upgrade when rbac token is invalid

- plans/convert.pp
- types/convertsteps.pp
> (PE-39429) Only restart puppetdb on non-legacy compilers

- tasks/agent_install.sh
The PT_install_flags variable is known to contain special characters, which may not be deterministically resolved by the shell unless escaped. It is recommended to quote such variables when using in conjunction with `echo`.
> The unquoted variable is essentially one long character class, [...], and it will match any single-letter filename in the current directory whose name occurs in within the brackets.
[source](https://unix.stackexchange.com/questions/785504/why-does-the-environment-variable-change-based-on-pwd#comment1505210_785504)
- https://unix.stackexchange.com/a/347954/663749
- https://unix.stackexchange.com/questions/785504/why-does-the-environment-variable-change-based-on-pwd#comment1505199_785504
- https://portal.perforce.com/s/detail/500PA00000FWMszYAH
> fix: echo environment variable containing special char

- plans/subplans/component_install.pp
Component install missing additional cert to show compilers aren't legacy
> (MAINT) Add compiler missing legacy false

- tasks/agent_install.sh
When running the peadm::agent_install shell task, fail the task if the curl command fails.
Ensure a curl failure when attempting to install the agent results in a failure of the task. Otherwise,
the task will report success regardless, leading to confusing and misleading failures in following
steps during the install.
> Check for curl failure

- documentation/recovery.md
##Summary
https://perforce.atlassian.net/browse/PE-39730 outlines some required changes to the procedure for replacing a missing or failed replica Puppet server. This draft attempts to address all issues raised in the ticket.
> Updates to recovery.md to address PE-39730

- .sync.yml
- Gemfile
- metadata.json
Based on https://github.com/puppetlabs/puppetlabs-puppet_agent/pull/743 to fix an issue with the version 0.7.1 of orchestrator_client
"The 0.7.1 release of orchestrator_client broadened its dependency on Faraday (see https://github.com/puppetlabs/orchestrator_client-ruby/commit/6f8661e). This change has caused Bundler to resolve Faraday in unexpected ways when there are other Gems with dependencies on Faraday.
This commit constrains orchestrator_client to < 0.7.1 until this issue is resolved."
https://github.com/rubygems/rubygems/issues/8286
> (maint) Constrain orchestrator_client to < 0.7.1

- REFERENCE.md
- plans/install.pp
- plans/subplans/install.pp
- plans/upgrade.pp
- types/download_mode.pp
This allows users of PEADM to reuse the type and validate their input properly before calling peadm.
> Move download_type enum to own type alias

- tasks/get_peadm_config.rb
Adds a lookup of the pe_build file to provide the PE version in the hash
returned by the get_peadm_config task.
We will use this in add_database and backup/restore plans as a version
gate for handling the newer host_action_collector database that is only
present in PE 2023.7+, for example.
Debated this; get_peadm_config task doesn't currently have a spec. I could certainly add one, if we'd like to expand the coverage there, but it's quite a bit more code than the pe_version addition :)
> (PE-39352) Add version to get peadm config

- functions/assert_supported_bolt_version.pp
> Add support for bolt 4.x

- .github/workflows/test-add-compiler-matrix.yml
- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica-matrix.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install-rhel-9.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-legacy-compilers.yaml
- .github/workflows/test-legacy-upgrade.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- REFERENCE.md
- documentation/install.md
- functions/assert_supported_pe_version.pp
- plans/install.pp
- spec/functions/assert_supported_pe_version_spec.rb
- spec/plans/subplans/install_spec.rb
Added PE 2025.0 as a supported PE version and to the test matrices. Also changed the default version to PE 2023
Do not merge until PE 2025 is officially released
> (PE-39891) Add support for PE 2025

- REFERENCE.md
- functions/pe_db_names.pp
- plans/add_database.pp
This commit updates the add_database plan to include the pe-patching and pe-hac databases when it cleans up the original postgres on the primary.
The add_database plan uses pg_basebackup to copy the entire contents of the postgres DB from the original primary DB to the new DB node's postgres. That process doesn't individually update a list of databases, so there's no context of "which DBs to move", because it just moves everything. However, during the cleanup process on the original DB That exists on the primary, the plan _does_ need to list the individual internal postgres dbs that need to be deleted.
> (PE-39351) Update add_database plan to work with patching/HAC

- .github/workflows/test-replace-failed-postgresql.yaml
- plans/replace_failed_postgresql.pp
- spec/acceptance/peadm_spec/plans/test_replace_failed_postgres.pp
- spec/docker/bolt-project.yaml
add CI test for replacing a failed postgres server on an XL deployment with DR enabled
Adding a new test in CI which sets up an XL deployment with DR enabled and then switches out a 'failed' postgres server for a replacement server
> (PE-40222) add CI test for replacing a failed postgres server

- REFERENCE.md
- plans/migrate.pp
This commit extends the existing migration plan by adding an optional upgrade
step after the migration is complete. If an upgrade version is specified, the 
plan will automatically perform an upgrade to the new version using the 
peadm::upgrade plan.
This commit extends the migration plan to support and utilise an
optional new replica host parameter. Code has also been added to purge
old nodes from the newly restored infrastructure.
> (PE-40372/3) Add optional upgrade and replica support to migration plan

- .github/workflows/test-migration.yaml
- spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
- spec/acceptance/peadm_spec/plans/test_migration.pp
Add github action to test migration plan for Standard architecture
> (PE-40379) CI to test Standard migration

- .github/workflows/auto_release.yml
- .github/workflows/spec.yml
- .github/workflows/test-add-compiler-matrix.yml
- .github/workflows/test-add-compiler.yaml
- .github/workflows/test-add-replica-matrix.yaml
- .github/workflows/test-add-replica.yaml
- .github/workflows/test-backup-restore-migration.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-latest-dev.yaml
- .github/workflows/test-install-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install-rhel-9.yaml
- .github/workflows/test-install.yaml
- .github/workflows/test-legacy-compilers.yaml
- .github/workflows/test-legacy-upgrade.yaml
- .github/workflows/test-replace-failed-postgresql.yaml
- .github/workflows/test-upgrade-latest-dev.yaml
- .github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
Updated our Github Action workflows to use ubuntu-latest rather than ubuntu-20.04. 
> (PE-40535) Github Actions deprecated Ubuntu 20.04 support

- REFERENCE.md
- plans/subplans/configure.pp
- tasks/pe_ldap_config.json
- tasks/pe_ldap_config.rb
As rbac-api/v1/ds has been deprecated, and remove in 2023.8, we need to utilise the new endpoint. Adding case for installs of versions 23.8 and above to use rbac-api/v1/command/ldap/create.
https://github.com/puppetlabs/puppetlabs-peadm/issues/498
> (PE-39397) Adding LDAP endpoint for 2023.8

- .github/workflows/test-add-compiler-matrix.yml
- .github/workflows/test-add-replica-matrix.yaml
- .github/workflows/test-backup-restore.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-install-rhel-9.yaml
- .github/workflows/test-legacy-compilers.yaml
- .github/workflows/test-legacy-upgrade.yaml
- .github/workflows/test-migration.yaml
- .github/workflows/test-replace-failed-postgresql.yaml
- .github/workflows/test-upgrade-matrix.yaml
- functions/assert_supported_pe_version.pp
Adding support for PE 2025.2.0
PE-40785
- [] Yes
> (RE-16847) add support for PE 2025.2.0

- REFERENCE.md
- functions/migration_opts_default.pp
- plans/migrate.pp
- plans/restore.pp
- spec/plans/restore_spec.rb
There were a few issues with restoring rbac:
1. the code was not looking in the right location to restore the keys.json file
2. on the system we migrate to the rbac token was revoked so the `puppet-db import` command was failing
> (PE-40379) fix issue on RBAC restore

- .fixtures.yml
- functions/pe_db_names.pp
Adding the Infra Assistant DB following just as was done with PE Patching in https://github.com/puppetlabs/puppetlabs-peadm/pull/531.
> (PE-40508) Add infra-assistant to add_database plan

- .fixtures.yml
- .github/workflows/test-migration.yaml
- .github/workflows/test-upgrade-matrix.yaml
- REFERENCE.md
- plans/add_database.pp
- plans/migrate.pp
- spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
- spec/acceptance/peadm_spec/plans/test_migration.pp
> (PE-40386) Phase 3 - Migrate to XL

- REFERENCE.md
- functions/log_plan_parameters.pp
- lib/puppet/functions/peadm/module_version.rb
- plans/install.pp
- plans/migrate.pp
- plans/replace_failed_postgresql.pp
- plans/upgrade.pp
- spec/plans/install_spec.rb
Parameters requested to be added to log in upgrade and install plans:
[] The peadm version being used
[] The nodes involved in the plan and their assigned roles
[] The PE version being installed.
[] The PE version being upgraded.
> (PE-40350) add plan parameters to log stream

- .github/workflows/test-failover.yaml
- .github/workflows/test-fips-install-matrix.yaml
- .github/workflows/test-install-matrix.yaml
- .github/workflows/test-upgrade-matrix.yaml
- .github/workflows/test-upgrade.yaml
Removing 2019 tests from matrices - taking up a lot of time testing a PE version we no longer support
> (MAINT) remove 2019 tests from matrices

- REFERENCE.md
- plans/migrate.pp
Make the peadm::migrate plan public
- [] Yes
> (PE-41176) make migrate plan public

- .github/workflows/test-replace-failed-postgresql.yaml
- plans/replace_failed_postgresql.pp
- spec/acceptance/peadm_spec/plans/test_replace_failed_postgres.pp
The Bolt plan for replacing a failed postgres host was not working properly when the primary was the host that had failed.
> (PE-41341) Allow primary postgres host to be the failure

- documentation/migration/migrating.md
Adding a Mark Down document to outline usage of the migrate plan
- [] Yes
> (PE-40391) Adding repo docs for migrate plan
