puppetlabs/puppetlabs-peadm

tasks/configure_node_groups.json
tasks/configure_node_groups.pp
tasks/configure_node_groups.sh

This will allow env to be not managed and use the production env for the apply.

Force prod run

---

CHANGELOG.md
functions/validate_version.pp
lib/puppet/functions/peadm/parsehocon.rb
plans/upgrade.pp

Bug fixes for upgrade plan going to 2019.8 release(s)

Fix upgrade peconf

---

CHANGELOG.md
plans/convert.pp

Fix bug in convert plan version validation

---

plans/action/install.pp

Implement changes to Plan[peadm::action::install] to take advantage of
expiremental parallelize() function to facilitate code clean-up and
determine if it can be used to improve performance of PE installation
process.

Make use of parallelize() function

---

README.md
documentation/classification.md
documentation/provision.md

* Update docs for bolt 3.x and new auto module dependency download
* Updated version of supported bolt
* Detailed more usage of staging directory

Updated docs to reflect bolt 3.5 usage

---

spec/fixtures/plans/pe_conf.json
spec/plans/convert_spec.rb
spec/plans/util/sanitize_pg_pe_conf_spec.rb

Last tests added with pending will raise further tickets

(SOLARCH-278) put pending on these tests due to function issues

---

spec/plans/convert_spec.rb
spec/plans/util/sanitize_pg_pe_conf_spec.rb

This PR should resolve linting issues causing rubocop to fail

Resolving linting issues

---

plans/action/install.pp

This cleans up some of what was ugly with parallelize() now that background() and wait() are available.

Add further parallelization to install subplan

---

.github/workflows/test-upgrade.yaml
documentation/pre_post_checks.md
spec/acceptance/peadm_spec/plans/upgrade_test_cluster.pp

* Updates the documentation/pre_post_checks links to litmus

SOLARCH-589: Write an acceptance test for the PEADM upgrade plan

---

.github/workflows/auto_release.yml
.gitlab-ci.yml
.travis.yml
Rakefile
appveyor.yml
metadata.json
pdk.yaml

PDK 2.2.0 update

---

.github/workflows/test-install-matrix.yaml
.github/workflows/test-install.yaml
.github/workflows/test-upgrade.yaml
README.md
documentation/install.md
functions/assert_supported_pe_version.pp
spec/plans/subplans/install_spec.rb

Adds support for the newly released versions

Support PE 2021.6 and 2019.8.11

---

documentation/classification.md

Images had name changed due to harmful language and the links were not updated here. Resolving

Repairing broken images

---

README.md

Clarify that customers can use the module on their own, and to encourage contributions

Update Readme to clarify support expectations

---

.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
plans/upgrade.pp
spec/acceptance/peadm_spec/plans/upgrade_test_cluster.pp

Two workflows which can access development builds on PE and ensure we can upgrade to them from a current release

Provide capability to do development upgrade tests

---

.github/workflows/test-add-compiler.yaml
spec/acceptance/peadm_spec/plans/add_compiler.pp
spec/acceptance/peadm_spec/plans/provision_test_cluster.pp

New worflow for on demand validation of the peadm::add_compiler plan and supporting other changes.

New test for adhoc add_compiler testing

---

.github/workflows/test-add-compiler.yaml
.github/workflows/test-add-replica.yaml
.github/workflows/test-failover.yaml
.github/workflows/test-fips-install-matrix.yaml
.github/workflows/test-install-matrix.yaml
.github/workflows/test-install.yaml
.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
.github/workflows/test-upgrade-matrix.yaml
.github/workflows/test-upgrade.yaml
REFERENCE.md
documentation/upgrade.md
plans/install.pp
spec/functions/assert_supported_pe_version_spec.rb
spec/plans/convert_spec.rb
spec/plans/upgrade_spec.rb

This PR is based of the previous iteration and a search and replace in vs code

Update 2021.7.1 to 2021.7.2 for LTS

---

Gemfile
metadata.json

Accidentally did'nt regenerate the gemfile

changelog_generator gemfile update

---

.github/workflows/test-add-compiler.yaml
.github/workflows/test-add-replica.yaml
.github/workflows/test-backup-restore.yaml
.github/workflows/test-failover.yaml
.github/workflows/test-fips-install-matrix.yaml
.github/workflows/test-install-matrix.yaml
.github/workflows/test-install.yaml
.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
.github/workflows/test-upgrade-matrix.yaml
.github/workflows/test-upgrade.yaml
REFERENCE.md
documentation/upgrade.md
functions/assert_supported_pe_version.pp
plans/install.pp
spec/functions/assert_supported_pe_version_spec.rb
spec/plans/convert_spec.rb
spec/plans/upgrade_spec.rb

Updated LTS version to 2021.7.3, updated newest to 2023.1.0, and modified tests to include 2023.

(PE-36091) Updating PE-ADM Supported Version

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.sync.yml
metadata.json

PDK version updated to 3.0.0
ci and nightly jobs added to github workflow

PE-36459 .sync.yml and pdk updated

---

metadata.json

Dependencies updates in metadata.json

PE-3PE-36464 metadata updated

---

.puppet-lint.rc
functions/generate_pe_conf.pp
plans/subplans/db_populate.pp
plans/subplans/modify_certificate.pp
plans/upgrade.pp
plans/util/retrieve_and_upload.pp

Removing global lint ignores.
.
.

(PE-336463)Puppet Lint Updates

---

.github/workflows/mend.yml

(#PE-16944) Correct Mend project

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

Stop using docker for our CI. Centos image always gets troubles.

(PE-37164) Fix Centos 7 CI issues

---

REFERENCE.md
functions/convert_hash.pp
functions/determine_status.pp
plans/status.pp

@example tag requires a description, otherwise puppet-strings leaves trailing spaces

fix trailing spaces

---

.github/workflows/test-install-rhel-9.yaml
README.md
metadata.json

Updating operating systems to include AlmaLinux 8 and RHEL 9.
Added tests for RHEL 9.
Updated compatibility in docs.

Updating operating systems in metadata.json

---

REFERENCE.md
plans/add_compiler.pp

Remove experimental status of add_compiler plan, change to public and update reference.md
[Jira ticket ](https://perforce.atlassian.net/browse/PE-37236)

(PE-37236) Remove experimental status of add_compiler

---

.github/workflows/test-backup-restore.yaml

This looks like it should work with the `pull_request` event

[ITHELP-87329] Update test-backup-restore.yaml

---

spec/functions/certname_spec.rb

This was previously disabled because it didn't pass on travis. Let's see how it works on GitHub Actions.

certname(): reenable test

---

tasks/get_peadm_config.rb

Added legacy compilers section, and updated compilers with legacy compilers oid

(PE-38767) Adding legacy compilers to get_peadm_config

---

REFERENCE.md
plans/install.pp
plans/subplans/install.pp
plans/upgrade.pp

pe_installer_source: Use Stdlib::HTTPSUrl datatype

---

metadata.json

Add AlmaLinux/CentOS 9 support

---

.github/workflows/test-add-compiler.yaml
.github/workflows/test-add-replica.yaml
.github/workflows/test-backup-restore-migration.yaml
.github/workflows/test-backup-restore.yaml
.github/workflows/test-failover.yaml
.github/workflows/test-fips-install-matrix.yaml
.github/workflows/test-install-latest-dev.yaml
.github/workflows/test-install-latest-xlarge-dev-nightly.yaml
.github/workflows/test-install-matrix.yaml
.github/workflows/test-install-rhel-9.yaml
.github/workflows/test-install.yaml
.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
.github/workflows/test-upgrade-matrix.yaml
.github/workflows/test-upgrade.yaml
spec/acceptance/peadm_spec/plans/install_test_cluster.pp

Moving workflows install password to secrets

(PE-38653) Moving workflows install password to secrets

---

documentation/add_replica.md

Updating add_replica docs with text changes

(PE-38817) Text fixes for add_replica docs

---

.github/workflows/test-add-compiler-matrix.yml
.github/workflows/test-add-compiler.yaml
REFERENCE.md
documentation/add_compiler.md
documentation/expanding.md
plans/add_compiler.pp
spec/acceptance/peadm_spec/plans/add_compiler.pp
spec/acceptance/peadm_spec/plans/provision_test_cluster.pp
spec/plans/add_compiler_spec.rb

Adding official support of compiler plan.

(PE-37233-35) Official support of Add compiler plan

---

documentation/classification.md
documentation/convert.md
documentation/upgrade.md

Also added additional legacy compiler updates to classification docs

(PE-38802) Adding note about PE Infra agent group purge

---

REFERENCE.md
plans/convert.pp
plans/upgrade.pp
types/convertsteps.pp
types/upgradesteps.pp

This makes the whole plan more readable because we don't need multiple lines in the plan.

peadm::convert & peadm::upgrade: move steps to own datatypes

---

metadata.json

(PE-38076) Remove bolt_shim and apply_helpers modules

---

.github/workflows/test-add-compiler-matrix.yml
.github/workflows/test-add-compiler.yaml
.github/workflows/test-add-replica-matrix.yaml
.github/workflows/test-add-replica.yaml
.github/workflows/test-failover.yaml
.github/workflows/test-fips-install-matrix.yaml
.github/workflows/test-install-matrix.yaml
.github/workflows/test-install-rhel-9.yaml
.github/workflows/test-install.yaml
.github/workflows/test-legacy-upgrade.yaml
.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
.github/workflows/test-upgrade-matrix.yaml
REFERENCE.md
plans/install.pp
spec/plans/subplans/install_spec.rb

Adding support for PE 2023.8.1

(PE-40187) Add support for PE 2023.8.1

---

CODEOWNERS

Adding platypus team to codeowners

---

.github/workflows/test-migration.yaml
plans/add_replica.pp

Add large and large with DR architectures to test migration workflow

PE-40380 Phase 2 (CI) migrate to large, no DR

---

.github/workflows/test-migration.yaml

add array entry to run the test migration on large with an upgrade

(PE-40382) Phase 2 (CI) migrate to large with PE upgrade

---

plans/migrate.pp

When performing manual testing of migrations on Large installations we found that when DR is enabled then after migration the new nodes we migrated to do not have the puppet agent enabled and puppet runs fail. Adding in a command at the end of the migration plan to ensure the puppet agent is enabled on these nodes fixes this issue. 
- [] Yes

(PE-40934) Ensure agent is enabled on new nodes we migrated to

---

.github/workflows/test-add-compiler-matrix.yml
.github/workflows/test-add-compiler.yaml
.github/workflows/test-add-replica-matrix.yaml
.github/workflows/test-add-replica.yaml
.github/workflows/test-backup-restore.yaml
.github/workflows/test-failover.yaml
.github/workflows/test-fips-install-matrix.yaml
.github/workflows/test-install-matrix.yaml
.github/workflows/test-install-rhel-9.yaml
.github/workflows/test-install.yaml
.github/workflows/test-legacy-compilers.yaml
.github/workflows/test-legacy-upgrade.yaml
.github/workflows/test-migration.yaml
.github/workflows/test-replace-failed-postgresql.yaml
.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
.github/workflows/test-upgrade-matrix.yaml
.github/workflows/test-upgrade.yaml
functions/assert_supported_pe_version.pp

Adding support for PE 2025.3.0 and 2023.8.3
RE-16873

(RE-16872) add support for PE 2025.3.0 and 2023.8.3

---

.github/workflows/test-add-compiler-matrix.yml
.github/workflows/test-add-compiler.yaml
.github/workflows/test-add-replica-matrix.yaml
.github/workflows/test-add-replica.yaml
.github/workflows/test-backup-restore.yaml
.github/workflows/test-failover.yaml
.github/workflows/test-fips-install-matrix.yaml
.github/workflows/test-install-matrix.yaml
.github/workflows/test-install-rhel-9.yaml
.github/workflows/test-install.yaml
.github/workflows/test-legacy-compilers.yaml
.github/workflows/test-legacy-upgrade.yaml
.github/workflows/test-migration.yaml
.github/workflows/test-replace-failed-postgresql.yaml
.github/workflows/test-upgrade-latest-dev.yaml
.github/workflows/test-upgrade-latest-xlarge-dev-nightly.yaml
.github/workflows/test-upgrade-matrix.yaml
.github/workflows/test-upgrade.yaml
REFERENCE.md
functions/assert_supported_pe_version.pp
plans/install.pp
spec/plans/subplans/install_spec.rb

Adding support for PE 2023.8.4 and 2025.4.0
RE-16889 and RE-16897

(PE-41546) add support for PE 2023.8.4 and 2025.4.0

---

functions/pe_db_names.pp

Adds the pe-workflow DB targeted for PE >=2025.6.0

(PE-41731) Add pe-workflow database
